-- PostgreSQL Production Database Schema for CloudScale Infotech Solutions
-- Domain Architecture: Clinical Diagnostics & LIS Telemetry (healthcare)
-- Generated by BizzMitra AI Engine
-- Problem Statement Reference:
-- "We are a growing IT & Software Services agency with 45 engineers managing 20+ concurrent enterprise client projects. Our client onboarding, sprint scope approvals, change requests, and SLA milestone tracking are currently scattered across fragmented email threads, Slack channels, and unversioned Google Sheets.   This causes frequent scope creep, delayed billable milestone sign-offs, lost invoice approvals, and client disputes regarding deliverables. We urgently need a centralized digital client delivery & project governance portal with automated SLA tracking, milestone approval workflows, role-based client & engineering dashboards, and real-time audit reporting."

CREATE TABLE IF NOT EXISTS public.healthcare_records (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  col1_data TEXT NOT NULL, -- Semantic Mapping: Test Investigation Panel
  col2_data TEXT NOT NULL, -- Semantic Mapping: Analyzer Instrument ID
  status TEXT NOT NULL,    -- Semantic Mapping: Laboratory Stage
  badge TEXT DEFAULT 'Active',
  assignee TEXT NOT NULL,  -- Semantic Mapping: Pathologist Lead
  metric_value TEXT NOT NULL, -- Semantic Mapping: Report TAT SLA
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.healthcare_records ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.healthcare_records
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Team and Role Authentication table
CREATE TABLE IF NOT EXISTS public.healthcare_users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  badge TEXT NOT NULL,
  department TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.healthcare_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read-write for authenticated users"
  ON public.healthcare_users
  FOR ALL
  USING (true)
  WITH CHECK (true);
